---

- hosts: workstations
  roles:
    - dev_tools
    - { role: offline_host, when: hw_type == 'laptop' }
    - { role: laptop, when: hw_type == 'laptop' }
    - qemu_libvirt
    - desktop_env
    - { role: desktop_user, user: 'adrian' }

