---
# file: roles/dockerhost/tasks/main.yml

- name: Add the docker apt repository GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the docker apt repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update cache and install docker-ce package
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Add admin user account to docker group
  become: true
  user:
    name: "{{ admin_username }}"
    shell: /bin/bash
    groups: docker
    append: yes
